export interface AppTemplatePreset {
  id: string;
  name: string;
  desc: string;
  defaultPort?: string;
  defaultEnv?: string;
  defaultVolumes?: string;
  defaultCommand?: string;
  defaultNetwork?: string;
  restartPolicy?: string;
}

export interface AppTemplatePresentation {
  icon?: string;
  color?: string;
  installs?: number;
}

export interface AppTemplate {
  id: string;
  name: string;
  desc: string;
  category: string;
  icon?: string;
  presentation?: AppTemplatePresentation;
  image: string;
  defaultPort: string;
  defaultEnv: string;
  defaultVolumes?: string;
  defaultCommand?: string;
  defaultNetwork?: string;
  restartPolicy: string;
  popular: boolean;
  tags: string[];
  presets?: AppTemplatePreset[];
}

const BASE_APP_TEMPLATES: AppTemplate[] = [
  {
    id: "wordpress",
    name: "WordPress",
    desc: "Popular CMS for websites and blogs",
    category: "CMS",
    image: "wordpress:latest",
    defaultPort: "8080:80",
    defaultEnv:
      "WORDPRESS_DB_HOST=mysql:3306\nWORDPRESS_DB_NAME=wordpress\nWORDPRESS_DB_USER=wp\nWORDPRESS_DB_PASSWORD=changeme",
    defaultVolumes: "/srv/wordpress:/var/www/html",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["PHP", "MySQL"],
    presentation: {
      icon: "https://cdn.simpleicons.org/wordpress/21759B",
      installs: 1240,
    },
  },
  {
    id: "ghost",
    name: "Ghost",
    desc: "Modern publishing platform for blogs and memberships",
    category: "CMS",
    image: "ghost:5-alpine",
    defaultPort: "2368:2368",
    defaultEnv: "url=http://localhost:2368",
    defaultVolumes: "/srv/ghost:/var/lib/ghost/content",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Blog", "Node.js"],
    presentation: {
      icon: "https://cdn.simpleicons.org/ghost/21759B",
      installs: 870,
    },
  },
  {
    id: "strapi",
    name: "Strapi",
    desc: "Headless CMS for APIs, admin panels, and content workflows",
    category: "CMS",
    image: "strapi/strapi:latest",
    defaultPort: "1337:1337",
    defaultEnv: "NODE_ENV=production",
    defaultVolumes: "/srv/strapi:/srv/app",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Headless", "API"],
    presentation: {
      icon: "https://cdn.simpleicons.org/strapi/4945FF",
      installs: 620,
    },
  },
  {
    id: "drupal",
    name: "Drupal",
    desc: "Enterprise-grade CMS for structured content sites",
    category: "CMS",
    image: "drupal:10-apache",
    defaultPort: "8081:80",
    defaultEnv: "",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["PHP", "CMS"],
    presentation: {
      icon: "https://cdn.simpleicons.org/drupal/0678BE",
      installs: 410,
    },
  },
  {
    id: "nginx",
    name: "Nginx",
    desc: "High-performance web server and reverse proxy",
    category: "Web Server",
    image: "nginx:alpine",
    defaultPort: "80:80,443:443",
    defaultEnv: "",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["HTTP", "Proxy"],
    presentation: {
      icon: "https://cdn.simpleicons.org/nginx/009639",
      installs: 980,
    },
  },
  {
    id: "apache",
    name: "Apache HTTP Server",
    desc: "Classic and reliable HTTP web server",
    category: "Web Server",
    image: "httpd:2.4-alpine",
    defaultPort: "8082:80",
    defaultEnv: "",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["HTTP", "Static"],
    presentation: {
      icon: "https://cdn.simpleicons.org/apache/D22128",
      installs: 540,
    },
  },
  {
    id: "caddy",
    name: "Caddy",
    desc: "Automatic HTTPS web server with simple configuration",
    category: "Web Server",
    image: "caddy:2-alpine",
    defaultPort: "8083:80,8443:443",
    defaultEnv: "",
    defaultVolumes: "/srv/caddy/data:/data,/srv/caddy/config:/config",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["HTTPS", "TLS"],
    presentation: {
      icon: "https://cdn.simpleicons.org/caddy/1F88C0",
      installs: 760,
    },
  },
  {
    id: "nodejs",
    name: "Node.js App",
    desc: "Deploy any Node.js application easily",
    category: "Runtime",
    image: "node:20-alpine",
    defaultPort: "3000:3000",
    defaultEnv: "NODE_ENV=production\nPORT=3000",
    defaultVolumes: "/srv/node-app:/app",
    defaultCommand:
      'sh -c "cd /app && if [ -f package.json ]; then npm install && npm start; else tail -f /dev/null; fi"',
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Node", "JS"],
    presentation: {
      icon: "https://cdn.simpleicons.org/nodedotjs/5FA04E",
      installs: 650,
    },
  },
  {
    id: "bun",
    name: "Bun Runtime",
    desc: "Fast JavaScript and TypeScript runtime for modern apps",
    category: "Runtime",
    image: "oven/bun:1",
    defaultPort: "3001:3000",
    defaultEnv: "NODE_ENV=production\nPORT=3000",
    defaultVolumes: "/srv/bun-app:/app",
    defaultCommand:
      'sh -c "cd /app && if [ -f package.json ]; then bun install && (bun run start || bun run dev --host 0.0.0.0 --port 3000); else tail -f /dev/null; fi"',
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Bun", "TS"],
    presentation: {
      icon: "https://cdn.simpleicons.org/bun/5FA04E",
      installs: 260,
    },
  },
  {
    id: "python-fastapi",
    name: "FastAPI",
    desc: "Python ASGI runtime template for API services",
    category: "Runtime",
    image: "tiangolo/uvicorn-gunicorn-fastapi:python3.11",
    defaultPort: "8000:80",
    defaultEnv: "MODULE_NAME=app.main\nPORT=80",
    defaultVolumes: "/srv/fastapi:/app",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Python", "API"],
    presentation: {
      icon: "https://cdn.simpleicons.org/fastapi/009688",
      installs: 330,
    },
  },
  {
    id: "php-fpm",
    name: "PHP-FPM",
    desc: "PHP FastCGI Process Manager",
    category: "Runtime",
    image: "php:8.3-fpm-alpine",
    defaultPort: "9000:9000",
    defaultEnv:
      "PHP_MEMORY_LIMIT=256M\nPHP_UPLOAD_MAX_FILESIZE=50M\nPHP_POST_MAX_SIZE=50M\nTZ=UTC",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["PHP", "FPM"],
    presentation: {
      icon: "https://cdn.simpleicons.org/php/777BB4",
      installs: 290,
    },
  },
  {
    id: "codeigniter",
    name: "CodeIgniter4",
    desc: "PHP framework template for building web applications with CodeIgniter 4",
    category: "Framework",
    image: "shinsenter/codeigniter4:php8.2-apache",
    defaultPort: "8081:80",
    defaultEnv: "CI_ENVIRONMENT=production",
    defaultVolumes: "/srv/codeigniter4:/app",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["PHP", "Framework", "CodeIgniter"],
    presentation: {
      icon: "https://cdn.simpleicons.org/codeigniter/FF2D20",
    },
  },
  {
    id: "laravelfans",
    name: "Laravel Fans",
    desc: "PHP framework starter image with writable project volume and Laravel-ready presets from laravelfans",
    category: "Framework",
    image: "laravelfans/laravel:12.58.0-dev",
    defaultPort: "8001:8000",
    defaultEnv:
      "APP_NAME=Laravel\nAPP_ENV=production\nAPP_DEBUG=false\nAPP_URL=http://localhost:8001\nLARAVEL_DATABASE_HOST=mysql\nLARAVEL_DATABASE_PORT_NUMBER=3306\nLARAVEL_DATABASE_NAME=laravel\nLARAVEL_DATABASE_USER=laravel\nLARAVEL_DATABASE_PASSWORD=secret",
    defaultVolumes: "/srv/laravel:/laravel/laravel",
    defaultCommand:
      "sh -c 'cd /laravel/laravel && if [ ! -f artisan ]; then echo \"Laravel not found, initializing...\"; composer create-project laravel/laravel .; fi && until php artisan migrate --force; do echo Waiting-DB...; sleep 5; done && php artisan serve --host=0.0.0.0 --port=8000'",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["PHP", "Framework", "Artisan"],
    presentation: {
      icon: "https://cdn.simpleicons.org/laravel/5CD04E",
      installs: 150,
    },
    presets: [
      {
        id: "dev",
        name: "Development",
        desc: "Enable debug mode and local-style environment values",
        defaultEnv:
          "APP_NAME=Laravel\nAPP_ENV=local\nAPP_DEBUG=true\nAPP_URL=http://localhost:8001\nLARAVEL_DATABASE_HOST=mysql\nLARAVEL_DATABASE_PORT_NUMBER=3306\nLARAVEL_DATABASE_NAME=laravel\nLARAVEL_DATABASE_USER=laravel\nLARAVEL_DATABASE_PASSWORD=secret",
        defaultVolumes: "/srv/laravel:/laravel/laravel",
        defaultCommand:
          "sh -c 'cd /laravel/laravel && if [ ! -f artisan ]; then echo \"Laravel not found, initializing...\"; composer create-project laravel/laravel .; fi && until php artisan migrate --force; do echo Waiting-DB...; sleep 5; done && php artisan serve --host=0.0.0.0 --port=8000'",
      },
      {
        id: "production",
        name: "Production",
        desc: "Hardened defaults for long-running production containers",
        defaultEnv:
          "APP_NAME=Laravel\nAPP_ENV=production\nAPP_DEBUG=false\nAPP_URL=https://example.com\nLARAVEL_DATABASE_HOST=mysql\nLARAVEL_DATABASE_PORT_NUMBER=3306\nLARAVEL_DATABASE_NAME=laravel\nLARAVEL_DATABASE_USER=laravel\nLARAVEL_DATABASE_PASSWORD=secret",
        defaultVolumes: "/srv/laravel:/laravel/laravel",
        defaultCommand:
          "sh -c 'cd /laravel/laravel && if [ ! -f artisan ]; then echo \"Laravel not found, initializing...\"; composer create-project laravel/laravel .; fi && until php artisan migrate --force; do echo Waiting-DB...; sleep 5; done && php artisan serve --host=0.0.0.0 --port=8000'",
        restartPolicy: "always",
      },
    ],
  },
  {
    id: "laravelbitnami",
    name: "Laravel Bitnami",
    desc: "PHP framework starter image with writable project volume and Laravel-ready presets from Bitnami",
    category: "Framework",
    image: "bitnami/laravel:latest",
    defaultPort: "8001:8000",
    defaultEnv:
      "APP_NAME=Laravel\nAPP_ENV=production\nAPP_DEBUG=false\nAPP_URL=http://localhost:8001\nLARAVEL_DATABASE_HOST=mysql\nLARAVEL_DATABASE_PORT_NUMBER=3306\nLARAVEL_DATABASE_NAME=laravel\nLARAVEL_DATABASE_USER=laravel\nLARAVEL_DATABASE_PASSWORD=secret",
    defaultVolumes: "/srv/laravel:/bitnami/laravel",
    defaultCommand:
      "sh -c 'cd /bitnami/laravel && if [ ! -f artisan ]; then echo \"Laravel not found, initializing...\"; composer create-project laravel/laravel .; fi && until php artisan migrate --force; do echo Waiting-DB...; sleep 5; done && php artisan serve --host=0.0.0.0 --port=8000'",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["PHP", "Framework", "Artisan"],
    presentation: {
      icon: "https://cdn.simpleicons.org/laravel/5CD04E",
      installs: 230,
    },
    presets: [
      {
        id: "dev",
        name: "Development",
        desc: "Enable debug mode and local-style environment values",
        defaultEnv:
          "APP_NAME=Laravel\nAPP_ENV=local\nAPP_DEBUG=true\nAPP_URL=http://localhost:8001\nLARAVEL_DATABASE_HOST=mysql\nLARAVEL_DATABASE_PORT_NUMBER=3306\nLARAVEL_DATABASE_NAME=laravel\nLARAVEL_DATABASE_USER=laravel\nLARAVEL_DATABASE_PASSWORD=secret",
        defaultVolumes: "/srv/laravel:/bitnami/laravel",
        defaultCommand:
          "sh -c 'cd /bitnami/laravel && if [ ! -f artisan ]; then echo \"Laravel not found, initializing...\"; composer create-project laravel/laravel .; fi && until php artisan migrate --force; do echo Waiting-DB...; sleep 5; done && php artisan serve --host=0.0.0.0 --port=8000'",
      },
      {
        id: "production",
        name: "Production",
        desc: "Hardened defaults for long-running production containers",
        defaultEnv:
          "APP_NAME=Laravel\nAPP_ENV=production\nAPP_DEBUG=false\nAPP_URL=https://example.com\nLARAVEL_DATABASE_HOST=mysql\nLARAVEL_DATABASE_PORT_NUMBER=3306\nLARAVEL_DATABASE_NAME=laravel\nLARAVEL_DATABASE_USER=laravel\nLARAVEL_DATABASE_PASSWORD=secret",
        defaultVolumes: "/srv/laravel:/bitnami/laravel",
        defaultCommand:
          "sh -c 'cd /bitnami/laravel && if [ ! -f artisan ]; then echo \"Laravel not found, initializing...\"; composer create-project laravel/laravel .; fi && until php artisan migrate --force; do echo Waiting-DB...; sleep 5; done && php artisan serve --host=0.0.0.0 --port=8000'",
        restartPolicy: "always",
      },
    ],
  },
  {
    id: "django",
    name: "Django",
    desc: "Python web framework template with Gunicorn and static file support",
    category: "Framework",
    image: "python:3.12-alpine",
    defaultPort: "8002:8000",
    defaultEnv: "DJANGO_SETTINGS_MODULE=app.settings\nPYTHONUNBUFFERED=1",
    defaultVolumes: "/srv/django:/app",
    defaultCommand:
      'sh -c "cd /app && if [ -f requirements.txt ]; then pip install -r requirements.txt; fi; python manage.py migrate 2>/dev/null || true; python manage.py runserver 0.0.0.0:8000"',
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Python", "Framework"],
    presentation: {
      icon: "https://cdn.simpleicons.org/django/092E20",
      installs: 410,
    },
  },
  {
    id: "flask",
    name: "Flask",
    desc: "Lightweight Python web framework template with Gunicorn",
    category: "Framework",
    image: "python:3.12-alpine",
    defaultPort: "8003:8000",
    defaultEnv:
      "FLASK_APP=app.py\nFLASK_ENV=production\nFLASK_RUN_HOST=0.0.0.0\nFLASK_RUN_PORT=8000\nPYTHONUNBUFFERED=1",
    defaultVolumes: "/srv/flask:/app",
    defaultCommand:
      'sh -c "cd /app && if [ -f requirements.txt ]; then pip install -r requirements.txt; fi; flask run --host=0.0.0.0 --port=8000"',
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Python", "Framework"],
    presentation: {
      icon: "https://cdn.simpleicons.org/flask/5FA04E",
      installs: 360,
    },
  },
  {
    id: "golang",
    name: "Golang",
    desc: "Go runtime template for building and running Go applications",
    category: "Runtime",
    image: "golang:1.20-alpine",
    defaultPort: "8080:8080",
    defaultEnv: "GO_ENV=production\nPORT=8080",
    defaultVolumes: "/srv/go-app:/app",
    defaultCommand:
      'sh -c "cd /app && if [ -f go.mod ]; then go mod tidy && go run main.go; else tail -f /dev/null; fi"',
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Go", "Golang", "Framework"],
    presentation: {
      icon: "https://cdn.simpleicons.org/goland/00ADD8",
      installs: 290,
    },
  },
  {
    id: "rust",
    name: "Rust",
    desc: "Rust runtime template for building and running Rust applications",
    category: "Runtime",
    image: "rust:1.70-alpine",
    defaultPort: "8080:8080",
    defaultEnv: "RUST_ENV=production\nPORT=8080",
    defaultVolumes: "/srv/rust-app:/app",
    defaultCommand:
      'sh -c "cd /app && if [ -f Cargo.toml ]; then cargo build && cargo run; else tail -f /dev/null; fi"',
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Rust", "Framework"],
    presentation: {
      icon: "https://cdn.simpleicons.org/rust/5FA04E",
      installs: 220,
    },
  },
  {
    id: "adguard-home",
    name: "AdGuard Home",
    desc: "Network-wide ad and tracker blocking DNS server",
    category: "Network",
    image: "adguard/adguardhome:latest",
    defaultPort: "3005:3000,53:53/tcp,53:53/udp",
    defaultEnv: "",
    defaultVolumes:
      "/srv/adguard/work:/opt/adguardhome/work,/srv/adguard/conf:/opt/adguardhome/conf",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["DNS", "Adblock"],
    presentation: {
      icon: "https://cdn.simpleicons.org/adguard/68BC71",
    },
  },
  {
    id: "pi-hole",
    name: "Pi-hole",
    desc: "Network-wide ad blocking and monitoring with web UI",
    category: "Network",
    image: "pihole/pihole:latest",
    defaultPort: "3006:80,53:53/tcp,53:53/udp",
    defaultEnv: "TZ=UTC\nWEBPASSWORD=changeme\nDNS1=8.8.8.8\nDNS2=8.8.4.4",
    defaultVolumes:
      "/srv/pihole:/etc/pihole,/srv/pihole-dnsmasq:/etc/dnsmasq.d",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["DNS", "Adblock"],
    presentation: {
      icon: "https://cdn.simpleicons.org/pihole/96060C",
    },
  },
  {
    id: "cloudflare-ddns",
    name: "Cloudflare DDNS",
    desc: "Dynamic DNS updater for Cloudflare-managed domains",
    category: "Network",
    image: "oznu/cloudflare-ddns:latest",
    defaultPort: "",
    defaultEnv:
      "API_KEY=replace-me\nEMAIL=replace-me\nZONE=example.com\nRECORD=home",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["DNS", "Dynamic DNS"],
    presentation: {
      icon: "https://cdn.simpleicons.org/cloudflare/F38020",
    },
  },
  {
    id: "cloudflare-tunnel",
    name: "Cloudflare Tunnel",
    desc: "Securely expose your local services to the internet via Cloudflare",
    category: "Network",
    image: "cloudflare/cloudflared:latest",
    defaultPort: "",
    defaultEnv: "TUNNEL_TOKEN=replace-me",
    defaultCommand: "tunnel --no-autoupdate run",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Network", "Tunnel"],
    presentation: {
      icon: "https://cdn.simpleicons.org/cloudflare/F38020",
    },
  },

  {
    id: "excalidraw",
    name: "Excalidraw",
    desc: "Virtual whiteboard for sketching and diagramming collaboratively",
    category: "Productivity",
    image: "excalidraw/excalidraw:latest",
    defaultPort: "5000:80",
    defaultEnv: "",
    defaultVolumes: "",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Whiteboard", "Diagram", "Collaboration"],
    presentation: {
      icon: "https://cdn.simpleicons.org/excalidraw/6965DB",
      installs: 430,
    },
  },

  {
    id: "php-8.1-apache",
    name: "PHP-8.1-Apache",
    desc: "Popular general-purpose scripting language especially suited to web development",
    category: "Language",
    image: "php:8.1-apache",
    defaultPort: "8081:80",
    defaultEnv:
      "PHP_MEMORY_LIMIT=256M\nPHP_UPLOAD_MAX_FILESIZE=50M\nPHP_POST_MAX_SIZE=50M\nTZ=UTC",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Database", "Admin"],
    presentation: {
      icon: "https://cdn.simpleicons.org/php/777BB4",
    },
  },
  {
    id: "phpmyadmin",
    name: "phpMyAdmin",
    desc: "Web-based MySQL/MariaDB administration tool",
    category: "Database",
    image: "phpmyadmin/phpmyadmin:latest",
    defaultPort: "8080:80",
    defaultEnv: "PMA_HOST=mysql",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Database", "Admin"],
    presentation: {
      icon: "https://cdn.simpleicons.org/phpmyadmin/6C78AF",
    },
  },
  {
    id: "phpmyadmin-dev",
    name: "phpMyAdmin (Development)",
    desc: "Web-based MySQL/MariaDB administration tool with development-friendly defaults",
    category: "Database",
    image: "phpmyadmin/phpmyadmin:latest",
    defaultPort: "8080:80",
    defaultEnv:
      "PMA_HOST=mysql\nPMA_USER=root\nPMA_PASSWORD=changeme\nPMA_ARBITRARY=1",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Database", "Admin"],
    presentation: {
      icon: "https://cdn.simpleicons.org/phpmyadmin/F38020",
      installs: 620,
    },
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    desc: "Powerful open-source object-relational database",
    category: "Database",
    image: "postgres:16-alpine",
    defaultPort: "5432:5432",
    defaultEnv:
      "POSTGRES_DB=mydb\nPOSTGRES_USER=admin\nPOSTGRES_PASSWORD=changeme",
    defaultVolumes: "/srv/postgres:/var/lib/postgresql/data",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["SQL", "DB"],
    presentation: {
      icon: "https://cdn.simpleicons.org/postgresql/4169E1",
      installs: 870,
    },
  },
  {
    id: "mysql",
    name: "MySQL",
    desc: "Widely used relational database for web applications",
    category: "Database",
    image: "mysql:8",
    defaultPort: "3306:3306",
    defaultEnv:
      "MYSQL_DATABASE=mydb\nMYSQL_USER=username\nMYSQL_PASSWORD=changeme\nMYSQL_ROOT_PASSWORD=changeme",
    defaultVolumes: "/srv/mysql:/var/lib/mysql",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["SQL", "InnoDB"],
    presentation: {
      icon: "https://cdn.simpleicons.org/mysql/4479A1",
      installs: 910,
    },
  },
  {
    id: "mariadb",
    name: "MariaDB",
    desc: "Open-source MySQL-compatible relational database",
    category: "Database",
    image: "mariadb:11",
    defaultPort: "3307:3306",
    defaultEnv:
      "MARIADB_DATABASE=mydb\nMARIADB_USER=username\nMARIADB_PASSWORD=changeme\nMARIADB_ROOT_PASSWORD=changeme",
    defaultVolumes: "/srv/mariadb:/var/lib/mysql",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["SQL", "MySQL"],
    presentation: {
      icon: "https://cdn.simpleicons.org/mariadb/003545",
      installs: 430,
    },
  },
  {
    id: "mongodb",
    name: "MongoDB",
    desc: "Document-based NoSQL database",
    category: "Database",
    image: "mongo:7",
    defaultPort: "27017:27017",
    defaultEnv:
      "MONGO_INITDB_ROOT_USERNAME=admin\nMONGO_INITDB_ROOT_PASSWORD=changeme",
    defaultVolumes: "/srv/mongodb:/data/db",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["NoSQL", "DB"],
    presentation: {
      icon: "https://cdn.simpleicons.org/mongodb/47A248",
      installs: 480,
    },
  },
  {
    id: "supabase-postgres",
    name: "Supabase PostgreSQL Engine",
    desc: "Lightweight Supabase setup using PostgreSQL only",
    category: "Database",
    image: "supabase/postgres:17.6.1.108-multigres",
    defaultPort: "5432:5432",
    defaultEnv:
      "POSTGRES_DB=postgres\nPOSTGRES_USER=postgres\nPOSTGRES_PASSWORD=changeme",
    defaultVolumes: "/srv/supabase-postgres:/var/lib/postgresql/data",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Database", "PostgreSQL", "Supabase"],
    presentation: {
      icon: "https://cdn.simpleicons.org/supabase/3ECF8E",
    },
  },
  {
    id: "supabase",
    name: "Supabase (All-in-One)",
    desc: "Unofficial all-in-one Supabase container",
    category: "Database",
    image: "khulnasoft/supabase-all-in-one:latest",
    defaultPort: "8000:8000,3000:3000,5432:5432",
    defaultEnv:
      "POSTGRES_DB=postgres\nPOSTGRES_USER=postgres\nPOSTGRES_PASSWORD=changeme\nJWT_SECRET=supersecretjwt\nSITE_URL=http://localhost\nAPI_EXTERNAL_URL=http://localhost:8000",
    defaultVolumes: "/srv/supabase:/data",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Database", "Supabase"],
    presentation: {
      icon: "https://cdn.simpleicons.org/supabase/3ECF8E",
    },
  },
  {
    id: "redis",
    name: "Redis",
    desc: "In-memory data structure store and cache",
    category: "Cache",
    image: "redis:7-alpine",
    defaultPort: "6379:6379",
    defaultEnv: "",
    defaultVolumes: "/srv/redis:/data",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Cache", "Queue"],
    presentation: {
      icon: "https://cdn.simpleicons.org/redis/DC382D",
      installs: 720,
    },
  },
  {
    id: "memcached",
    name: "Memcached",
    desc: "High-performance distributed memory object cache",
    category: "Cache",
    image: "memcached:1.6-alpine",
    defaultPort: "11211:11211",
    defaultEnv: "",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Cache", "Memory"],
    presentation: {
      installs: 190,
    },
  },
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    desc: "Reliable message broker with management UI",
    category: "Cache",
    image: "rabbitmq:3-management-alpine",
    defaultPort: "5672:5672,15672:15672",
    defaultEnv: "RABBITMQ_DEFAULT_USER=admin\nRABBITMQ_DEFAULT_PASS=changeme",
    defaultVolumes: "/srv/rabbitmq:/var/lib/rabbitmq",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Queue", "AMQP"],
    presentation: {
      icon: "https://cdn.simpleicons.org/rabbitmq/FF6600",
      installs: 510,
    },
  },
  {
    id: "grafana",
    name: "Grafana",
    desc: "Beautiful metrics dashboards and analytics",
    category: "Monitoring",
    image: "grafana/grafana:latest",
    defaultPort: "3000:3000",
    defaultEnv: "GF_SECURITY_ADMIN_PASSWORD=admin",
    defaultVolumes: "/srv/grafana:/var/lib/grafana",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Metrics", "UI"],
    presentation: {
      icon: "https://cdn.simpleicons.org/grafana/F46800",
      installs: 430,
    },
  },
  {
    id: "prometheus",
    name: "Prometheus",
    desc: "Open-source monitoring and alerting toolkit",
    category: "Monitoring",
    image: "prom/prometheus:latest",
    defaultPort: "9090:9090",
    defaultEnv: "",
    defaultVolumes: "/srv/prometheus:/prometheus",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Metrics", "Alert"],
    presentation: {
      icon: "https://cdn.simpleicons.org/prometheus/E6522C",
      installs: 390,
    },
  },
  {
    id: "loki",
    name: "Loki",
    desc: "Log aggregation system designed for Grafana",
    category: "Monitoring",
    image: "grafana/loki:latest",
    defaultPort: "3100:3100",
    defaultEnv: "",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Logs", "Grafana"],
    presentation: {
      icon: "https://cdn.simpleicons.org/grafana/F46800",
      installs: 180,
    },
  },
  {
    id: "uptime-kuma",
    name: "Uptime Kuma",
    desc: "Self-hosted uptime monitoring and status pages",
    category: "Monitoring",
    image: "louislam/uptime-kuma:1",
    defaultPort: "3002:3001",
    defaultEnv: "",
    defaultVolumes: "/srv/uptime-kuma:/app/data",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Uptime", "Status"],
    presentation: {
      icon: "https://cdn.simpleicons.org/uptimekuma/5CDD8B",
      installs: 520,
    },
  },
  {
    id: "beszel",
    name: "Beszel",
    desc: "A lightweight server monitoring hub with historical data, docker stats, and alerts.",
    category: "Monitoring",
    image: "henrygd/beszel:latest",
    defaultPort: "8080:8080",
    defaultEnv: "",
    defaultVolumes: "/srv/beszel:/data",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Monitoring", "Alert"],
  },

  {
    id: "traefik",
    name: "Traefik Proxy",
    desc: "Modern HTTP reverse proxy and load balancer",
    category: "Proxy",
    image: "traefik:v3",
    defaultPort: "80:80,443:443,8080:8080",
    defaultEnv:
      "TRAEFIK_API_DASHBOARD=true\nTRAEFIK_API_INSECURE=true\nTRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80\nTRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443\nTRAEFIK_PROVIDERS_DOCKER=true\nTRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false\nTRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL=you@example.com\nTRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_STORAGE=/letsencrypt/acme.json\nTRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_HTTPCHALLENGE=true\nTRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_HTTPCHALLENGE_ENTRYPOINT=web\nTRAEFIK_LOG_LEVEL=INFO",
    defaultVolumes:
      "/var/run/docker.sock:/var/run/docker.sock,/srv/traefik/letsencrypt:/letsencrypt/letsencrypt",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["HTTP", "SSL"],
    presentation: {
      icon: "https://cdn.simpleicons.org/traefikproxy/24A1C1",
      installs: 560,
    },
  },
  {
    id: "nginx-proxy-manager",
    name: "Nginx Proxy Manager",
    desc: "Reverse proxy manager with a friendly web UI",
    category: "Proxy",
    image: "jc21/nginx-proxy-manager:latest",
    defaultPort: "80:80,81:81,443:443",
    defaultEnv: "",
    defaultVolumes: "/srv/npm/data:/data,/srv/npm/letsencrypt:/etc/letsencrypt",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Proxy", "UI"],
    presentation: {
      icon: "https://cdn.simpleicons.org/nginxproxymanager/F15833",
      installs: 610,
    },
  },
  {
    id: "haproxy",
    name: "HAProxy",
    desc: "Battle-tested load balancer and TCP/HTTP proxy",
    category: "Proxy",
    image: "haproxy:2.9-alpine",
    defaultPort: "8404:8404,8084:80",
    defaultEnv: "",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Load Balancer", "L4/L7"],
  },
  {
    id: "minio",
    name: "MinIO",
    desc: "High-performance S3-compatible object storage",
    category: "Storage",
    image: "minio/minio:latest",
    defaultPort: "9000:9000,9001:9001",
    defaultEnv: "MINIO_ROOT_USER=minioadmin\nMINIO_ROOT_PASSWORD=changeme",
    defaultVolumes: "/srv/minio:/data",
    defaultCommand: "server /data --console-address :9001",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["S3", "Storage"],
    presentation: {
      icon: "https://cdn.simpleicons.org/minio/C72E49",
      installs: 210,
    },
  },
  {
    id: "nextcloud",
    name: "Nextcloud",
    desc: "Self-hosted collaboration and file sync platform",
    category: "Storage",
    image: "nextcloud:29-apache",
    defaultPort: "8085:80",
    defaultEnv: "PUID=1000\nPGID=1000\nTZ=UTC",
    defaultVolumes: "/srv/nextcloud:/var/www/html",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Files", "Collaboration"],
    presentation: {
      icon: "https://cdn.simpleicons.org/nextcloud/0082C9",
      installs: 700,
    },
  },
  {
    id: "filebrowser",
    name: "File Browser",
    desc: "Simple web-based file manager for server directories",
    category: "Storage",
    image: "filebrowser/filebrowser:latest",
    defaultPort: "8086:80",
    defaultEnv: "PUID=1000\nPGID=1000\nTZ=UTC\nFILEBROWSER_AUTH_METHOD=basic",
    defaultVolumes: "/srv/filebrowser:/srv",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Files", "UI"],
    presentation: {
      installs: 280,
    },
  },
  {
    id: "immich",
    name: "Immich",
    desc: "Self-hosted photo and video backup platform with external services configuration",
    category: "Storage",
    image: "ghcr.io/immich-app/immich-server:release",
    defaultPort: "2283:2283",
    defaultEnv:
      "TZ=UTC\nUPLOAD_LOCATION=/usr/src/app/upload\nDB_HOSTNAME=postgres\nDB_USERNAME=postgres\nDB_PASSWORD=changeme\nDB_DATABASE_NAME=immich\nREDIS_HOSTNAME=redis",
    defaultVolumes: "/srv/immich/library:/usr/src/app/upload",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Photos", "Backup", "Media"],
    presentation: {
      icon: "https://cdn.simpleicons.org/immich/4250AF",
      installs: 460,
    },
    presets: [
      {
        id: "library-only",
        name: "Library Only",
        desc: "Minimal filesystem preset for attaching an existing media path",
        defaultVolumes: "/srv/immich/library:/usr/src/app/upload",
      },
      {
        id: "external-services",
        name: "External DB + Redis",
        desc: "Preset for environments where Postgres and Redis already exist",
        defaultEnv:
          "TZ=UTC\nUPLOAD_LOCATION=/usr/src/app/upload\nDB_HOSTNAME=postgres.internal\nDB_USERNAME=immich\nDB_PASSWORD=changeme\nDB_DATABASE_NAME=immich\nREDIS_HOSTNAME=redis.internal",
        defaultVolumes: "/srv/immich/library:/usr/src/app/upload",
      },
    ],
  },
  {
    id: "n8n",
    name: "n8n",
    desc: "Workflow automation platform with built-in editor UI",
    category: "Automation",
    image: "n8nio/n8n:latest",
    defaultPort: "5678:5678",
    defaultEnv:
      "N8N_HOST=localhost\nN8N_PORT=5678\nN8N_PROTOCOL=http\nWEBHOOK_URL=http://localhost:5678/\nTZ=UTC",
    defaultVolumes: "/srv/n8n:/home/node/.n8n",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Workflow", "Automation", "Jobs"],
    presentation: {
      icon: "https://cdn.simpleicons.org/n8n/EA4B71",
      installs: 680,
    },
    presets: [
      {
        id: "basic",
        name: "Basic UI",
        desc: "Single-container setup for quick workflow testing",
      },
      {
        id: "reverse-proxy",
        name: "Behind Reverse Proxy",
        desc: "Preset for running n8n behind an existing HTTPS reverse proxy",
        defaultEnv:
          "N8N_HOST=n8n.example.com\nN8N_PORT=5678\nN8N_PROTOCOL=https\nWEBHOOK_URL=https://n8n.example.com/\nTZ=UTC",
      },
    ],
  },
  {
    id: "open-webui",
    name: "Open WebUI",
    desc: "AI assistant web UI for local or remote LLM backends",
    category: "AI",
    image: "ghcr.io/open-webui/open-webui:main",
    defaultPort: "3004:8080",
    defaultEnv:
      "WEBUI_SECRET_KEY=changeme\nOLLAMA_BASE_URL=http://host.docker.internal:11434",
    defaultVolumes: "/srv/open-webui:/app/backend/data",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["AI", "LLM", "Chat"],
    presentation: {
      installs: 590,
    },
    presets: [
      {
        id: "ollama-local",
        name: "Ollama Local",
        desc: "Preset for connecting to a host-level Ollama service",
        defaultEnv:
          "WEBUI_SECRET_KEY=changeme\nOLLAMA_BASE_URL=http://host.docker.internal:11434",
      },
      {
        id: "openai-compatible",
        name: "OpenAI-Compatible API",
        desc: "Preset for OpenAI-compatible remote inference endpoints",
        defaultEnv:
          "WEBUI_SECRET_KEY=changeme\nOPENAI_API_BASE_URL=https://api.openai.com/v1\nOPENAI_API_KEY=replace-me",
      },
    ],
  },
  {
    id: "openclaw",
    name: "OpenClaw official",
    desc: "OpenClaw is a self-hosted AI agent platform that provides Claude AI integration through a local gateway. It enables running AI assistants with local tool execution, file access, and workspace management. Features include WebSocket gateway, browser automation, and extensible command framework.",
    category: "AI",
    image: "ghcr.io/openclaw/openclaw:latest",
    defaultPort: "18789:18789",
    defaultEnv:
      "GATEWAY_CONTROLUI_ALLOWEDORIGINS=http://ip:18789,https://domain.com\nOPENCLAW_SECRET_KEY=changeme\nOPENCLAW_DB_URL=postgresql://postgres:changeme@postgres:5432/openclaw",
    defaultVolumes: "/srv/openclaw:/app/data",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["AI", "Agents", "Orchestration"],
    presentation: {
      icon: "https://openclaw.ai/favicon-32.png",
      installs: 750,
    },
  },
  {
    id: "openclaw-alpine",
    name: "OpenClaw Alpine (Community Edition)",
    desc: "OpenClaw Alpine is a lightweight version of the OpenClaw platform, optimized for minimal resource usage while maintaining core functionalities.",
    category: "AI",
    image: "alpine/openclaw:latest",
    defaultPort: "18790:18789",
    defaultEnv:
      "GATEWAY_CONTROLUI_ALLOWEDORIGINS=http://ip:18790,https://domain.com\nOPENCLAW_SECRET_KEY=changeme\nOPENCLAW_DB_URL=postgresql://postgres:changeme@postgres:5432/openclaw_alpine",
    defaultVolumes: "/srv/openclaw-alpine:/app/data",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["AI", "Agents", "Orchestration"],
    presentation: {
      icon: "https://openclaw.ai/favicon-32.png",
      installs: 750,
    },
  },
  {
    id: "9router",
    name: "9Router",
    desc: "9Router is a self-hosted AI agent orchestration platform that provides a local gateway for managing and routing requests to various LLM backends. It enables users to create, manage, and monitor AI agents with support for multiple models and dynamic routing based on request parameters. Features include a web-based dashboard, API access, and extensible plugin architecture.",
    category: "AI",
    image: "decolua/9router:latest",
    defaultPort: "20128:20128",
    defaultEnv: "PORT=20128\nNEXT_PUBLIC_BASE_URL=http://IP_SERVER:20128",
    defaultVolumes: "/srv/9router-data:/root/9router",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["AI", "Orchestration", "Management"],
    presentation: {
      icon: "https://cdn.simpleicons.org/openrouter/2496ED",
      installs: 480,
    },
    presets: [
      {
        id: "9router-development",
        name: "9Router Development",
        desc: "Preset with development-friendly defaults for local testing and iteration",
        defaultEnv: "PORT=20128\nNEXT_PUBLIC_BASE_URL=http://IP_SERVER:20128",
      },
      {
        id: "9router-production",
        name: "9Router Production",
        desc: "Preset optimized for production deployments with secure defaults",
        defaultEnv:
          "PORT=20128\nHOSTNAME=0.0.0.0\nNEXT_PUBLIC_BASE_URL=http://IP_SERVER:20128",
      },
    ],
  },
  {
    id: "docker",
    name: "Docker",
    desc: "Containerization platform for building, shipping, and running applications",
    category: "DevOps",
    image: "docker:latest",
    defaultPort: "2375:2375",
    defaultEnv: "DOCKER_TLS_CERTDIR=/certs",
    defaultVolumes: "/var/run/docker.sock:/var/run/docker.sock",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Container", "Docker"],
    presentation: {
      icon: "https://cdn.simpleicons.org/docker/2496ED",
    },
  },
  {
    id: "portainer",
    name: "Portainer",
    desc: "Docker container management UI",
    category: "DevOps",
    image: "portainer/portainer-ce:latest",
    defaultPort: "9000:9000",
    defaultEnv: "",
    defaultVolumes:
      "/var/run/docker.sock:/var/run/docker.sock,/srv/portainer:/data",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Docker", "UI"],
    presentation: {
      icon: "https://cdn.simpleicons.org/portainer/13BEF9",
      installs: 340,
    },
  },
  {
    id: "gitea",
    name: "Gitea",
    desc: "Lightweight self-hosted Git service with CI-friendly workflows",
    category: "DevOps",
    image: "gitea/gitea:1.22",
    defaultPort: "3003:3000,222:22",
    defaultEnv: "USER_UID=1000\nUSER_GID=1000",
    defaultVolumes: "/srv/gitea:/data",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["Git", "SCM"],
    presentation: {
      icon: "https://cdn.simpleicons.org/gitea/609926",
      installs: 590,
    },
  },
  {
    id: "jenkins",
    name: "Jenkins",
    desc: "Automation server for CI/CD pipelines",
    category: "DevOps",
    image: "jenkins/jenkins:lts-jdk17",
    defaultPort: "8087:8080,50000:50000",
    defaultEnv: "JAVA_OPTS=-Djenkins.install.runSetupWizard=false",
    defaultVolumes: "/srv/jenkins:/var/jenkins_home",
    restartPolicy: "unless-stopped",
    popular: true,
    tags: ["CI/CD", "Automation"],
    presentation: {
      icon: "https://cdn.simpleicons.org/jenkins/D24939",
      installs: 620,
    },
  },
  {
    id: "docker-registry",
    name: "Docker Registry",
    desc: "Private OCI-compatible image registry",
    category: "DevOps",
    image: "registry:2",
    defaultPort: "5000:5000",
    defaultEnv: "",
    defaultVolumes: "/srv/docker-registry:/var/lib/registry",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["OCI", "Registry"],
    presentation: {
      icon: "https://cdn.simpleicons.org/docker/2496ED",
      installs: 150,
    },
  },

  {
    id: "mailhog",
    name: "MailHog",
    desc: "Email testing tool with web UI and SMTP server",
    category: "DevOps",
    image: "mailhog/mailhog:latest",
    defaultPort: "8025:8025,1025:1025",
    defaultEnv: "",
    defaultVolumes: "",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Email", "Testing"],
    presentation: {
      icon: "https://cdn.simpleicons.org/maildotru/005FF9",
      installs: 220,
    },
  },
  {
    id: "redisinsight",
    name: "RedisInsight",
    desc: "GUI for Redis database management and monitoring",
    category: "DevOps",
    image: "redislabs/redisinsight:latest",
    defaultPort: "8004:8001",
    defaultEnv: "",
    defaultVolumes: "redisinsight-data:/db",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Redis", "GUI"],
    presentation: {
      icon: "https://cdn.simpleicons.org/redis/DC382D",
      installs: 200,
    },
  },
  {
    id: "redis-commander",
    name: "Redis Commander",
    desc: "Web-based Redis management tool",
    category: "DevOps",
    image: "rediscommander/redis-commander:latest",
    defaultPort: "8080:8081",
    defaultEnv: "REDIS_HOSTS=local:redis:6379",
    defaultVolumes: "",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Redis", "GUI"],
    presentation: {
      icon: "https://cdn.simpleicons.org/redis/DC382D",
      installs: 180,
    },
  },

  {
    id: "pgadmin",
    name: "pgAdmin",
    desc: "Web-based administration tool for PostgreSQL databases",
    category: "DevOps",
    image: "dpage/pgadmin4:latest",
    defaultPort: "8088:80",
    defaultEnv:
      "PGADMIN_DEFAULT_EMAIL=admin@example.com\nPGADMIN_DEFAULT_PASSWORD=admin\nPGADMIN_LISTEN_PORT=80\nPGADMIN_CONFIG_SERVER_MODE=True",
    defaultVolumes: "/srv/pgadmin:/var/lib/pgadmin",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["PostgreSQL", "GUI"],
    presentation: {
      icon: "https://cdn.simpleicons.org/postgresql/4169E1",
      installs: 270,
    },
  },
  {
    id: "adminer",
    name: "Adminer",
    desc: "Lightweight web-based database management tool",
    category: "DevOps",
    image: "adminer:latest",
    defaultPort: "8089:8080",
    defaultEnv: "",
    defaultVolumes: "",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Database", "GUI"],
    presentation: {
      icon: "https://cdn.simpleicons.org/adminer/8C7EE0",
      installs: 320,
    },
  },

  {
    id: "genieacs",
    name: "GenieACS",
    desc: "TR-069 remote management server for CPE devices",
    category: "DevOps",
    image: "genieacs/genieacs:latest",
    defaultPort: "7547:7547,7557:7557,7567:7567,3000:3000",
    defaultEnv:
      "GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo/genieacs\nGENIEACS_CWMP_ACCESS_LOG_FILE=/var/log/genieacs/cwmp-access.log\nGENIEACS_NBI_ACCESS_LOG_FILE=/var/log/genieacs/nbi-access.log\nGENIEACS_UI_JWT_SECRET=super-secret-key\nGENIEACS_CWMP_PORT=7547\nGENIEACS_NBI_PORT=7557\nGENIEACS_FS_PORT=7567\nGENIEACS_UI_PORT=3000",
    defaultVolumes:
      "/srv/genieacs/logs:/var/log/genieacs\n/srv/genieacs/ext:/opt/genieacs/ext",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["TR-069", "CPE", "Network"],
  },

  {
    id: "wuzapi",
    name: "WuzAPI",
    desc: "WuzAPI multi user and multi device REST API Service for Whatsapp.",
    category: "DevOps",
    image: "asternic/wuzapi:latest",
    defaultPort: "8080:8080",
    defaultEnv:
      "WUZAPI_ADMIN_TOKEN=your_32_byte_encryption_key_here\nDB_NAME=wuzapi\nDB_HOST=postgres\nDB_USER=postgres\nDB_PASSWORD=changeme\nDB_PORT=5432\nDB_SSLMODE=false",
    defaultVolumes: "/srv/wuzapi:/var/lib/wuzapi",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Messaging", "WhatsApp", "API"],
    presentation: {
      icon: "https://cdn.simpleicons.org/whatsapp/25D366",
      installs: 80,
    },
  },
  {
    id: "waha",
    name: "WhatsApp HTTP API (WAHA) Core",
    desc: "WAHA - WhatsApp HTTP API that you can install on your own server and run in less than 5 minutes!",
    category: "DevOps",
    image: "devlikeapro/waha:latest",
    defaultPort: "3000:3000",
    defaultEnv:
      "WHATSAPP_API_KEY=CHANGE_THIS_TO_RANDOM_32_CHAR\nWAHA_DASHBOARD_ENABLED=true\nWAHA_DASHBOARD_USERNAME=admin\nWAHA_DASHBOARD_PASSWORD=supersecretpassword",
    defaultVolumes:
      "/srv/waha/sessions:/app/.sessions,/srv/waha/media:/app/.media",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Messaging", "WhatsApp", "API"],
    presentation: {
      icon: "https://cdn.simpleicons.org/whatsapp/25D366",
      installs: 60,
    },
  },
  {
    id: "umami",
    name: "Umami",
    desc: "Simple, fast, privacy-focused web analytics",
    category: "DevOps",
    image: "umami-software/umami:latest",
    defaultPort: "3000:3000",
    defaultEnv: "DATABASE_URL=postgresql://umami:umami@postgres:5432/umami",
    defaultVolumes: "/srv/umami:/app/data",
    restartPolicy: "unless-stopped",
    popular: false,
    tags: ["Analytics", "Web"],
    presentation: {
      icon: "https://cdn.simpleicons.org/umami/00BFFF",
      installs: 50,
    },
  },
];

export const APP_TEMPLATES: AppTemplate[] = BASE_APP_TEMPLATES;
